### ISSUE TITLE
App release

### ISSUE THREAD

**Issue by PhilippMatthes** [kiliankoe/DVB#31]
Hi Kilian, if VVO is approving my App, then I'd like to publish it to the iOS App Store. Before I submit my App, I wanted to seek for approval from you. Can I use your API as a part of my App? The App will be free. I would like to mention you in the App description with the following sentence:

> Die Manni App nutzt mit freundlicher Genehmigung das VVO-Widget und die unter MIT Lizenz stehende API von Kilian Koeltzsch:
> https://github.com/kiliankoe/DVB

Is this ok?

**Comment by kiliankoe** [comment]
All this is is a wrapper for the VVO's WebAPI (with broken coordinate handling 🙈). The license permits pretty much anything anyways, but huge thanks nevertheless for the mention! 😊 

If you don't mind I'd update the text to say `die VVO WebAPI` instead of `das VVO Widget` and `Bibliothek` instead of `API`, thanks! 🖖 

Looking forward to using your app!

**Comment by PhilippMatthes** [comment]
Thank you very much, I will change the description text to fit your recommendations. Have a nice weekend!
