### ISSUE TITLE
Unknown mode of transport 'plusbus'.

### ISSUE THREAD

**Issue by marcusrossel** [kiliankoe/DVB#35]
Running

```swift
RouteChange.get { result in
    if let response = result.success {
        print(response.lines)
        print(response.changes)
    }
}
```

currently results in this message:

```plaintext
Unknown mode of transport 'plusbus', please open an issue on https://github.com/kiliankoe/DVB for this, thanks!
```

**Comment by kiliankoe** [comment]
Ah, I saw this being added, but haven't come around to the change here yet. `plusbus` basically just has to be added to [Mode.swift](https://github.com/kiliankoe/DVB/blob/master/Sources/DVB/Models/Mode.swift) to suppress the message, but everything else should still be working.

You're welcome to submit a PR for this if it's bothering you right now, otherwise it's on my list when I update this package again 😊 Thanks for the issue!

**Comment by marcusrossel** [comment]
I'll just submit a PR.

While I've got your attention... Where did you get the information for the DVB's web APIs?

**Comment by kiliankoe** [comment]
Thanks again for the PR!

Most of the info on the DVB APIs is reverse-engineered through several sources. I've tried my best at documenting what I know [here](https://github.com/kiliankoe/vvo). Feel free to add anything you might have found in addition to that 👍

**Comment by kiliankoe** [comment]
Oh, and of course please add whatever you're building (if applicable) to one of the lists at the bottom of the README 😊
