### ISSUE TITLE
Mobile DVB page as content source?

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/DVB#5]
https://m.dvb.de/de/abfahrtsmonitor/abfahrten.do?t=1&id=33000005&_=qHLvk

There's a bit more information there. Maybe this uses the EFA endpoint instead of the widgets stuff? Just something to think about.

**Comment by richardneitzke** [comment]
The EFA API does not provide any information about delays.

> Es wird immer die aktuelle Abfahrtszeit ausgegeben. In der Ausgabe wird nicht zwischen Echtzeit und Sollzeit unterschieden.

This is interesting because it means that the delay information is either calculated by them or they use a different API for it. Unfortunately the mobile site does not request the data itself but an inflated HTML page.

Their departure data sometimes varies from the EFA departure time too, by the way.
The only way I saw back when I did my research was writing a HTML scraper to have their delay information.

**Comment by kiliankoe** [comment]
Ah, thanks for the info!

I'm thinking of adding additional methods for scraping the pages (probably using [tid-kijyun/kanna](https://github.com/tid-kijyun/Kanna)) so that one can choose to use the _official_ API or the probably more error-prone page scraping with more data.

**Comment by richardneitzke** [comment]
Sounds reasonable.

Another thought I had was to host a ([Perfect](https://github.com/PerfectlySoft/Perfect)? - Keeping it Swift 😎) server that parses the mobile pages and transforms it into a REST-API. That way when the mobile site changes, the problem can be fixed by switching to the "official" API and updating the scraper code meanwhile. It would also reduce the amount of data downloaded on the device.

**Comment by kiliankoe** [comment]
Love the idea, and have previously pursued it 😄 See [simpledvb](https://github.com/kiliankoe/simpledvb) using [dvbjs](https://github.com/kiliankoe/dvbjs). Just without the scraping part. 

But it's definitely a worthwhile idea! Would love to explore this further in the future.

**Comment by richardneitzke** [comment]
Scraping the mobile page with the Kanna library seems to be a piece of cake, I just tried it. I'll just open a new repository for the server-sided scraping 😃

**Comment by kiliankoe** [comment]
This is no longer relevant as the new new mobile page is making use of an API and the official API access is around the corner anyways, rendering this issue completely obsolete.
